### ISSUE TITLE
ByuMapFragment: No padding on zoomToCampusWithMarkers

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#170] opened 2017-02-07 18:58 UTC
Name of Tester: Eric
Feature: AED Locator (all using zoomToCampusWithMarkers)

How to produce error:
There is no padding on the zoom of the map

Expected Result:
Both the user's location and the annotation should be visible

**Comment by romrell4** [comment] 2017-02-15 22:31
Duplicate of #153

**Closed** 2017-02-24 19:31 UTC
Labels: duplicate, enhancement
